/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : AE
*   Dependencies         : 
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 3.0.0
*   Build Version        : S32K3_RTD_3_0_0_D2303_ASR_REL_4_7_REV_0000_20230331
*
*   Copyright 2020 - 2023 NXP Semiconductors
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/
/*==================================================================================================
==================================================================================================*/
#ifndef CANTRCV_43_AE_CFG_H
#define CANTRCV_43_AE_CFG_H

/**
*   @file    CanTrcv_43_AE_Cfg.h
*   @version 3.0.0
*
*   @brief   AUTOSAR CanTrcv_43_AE - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup CANTRCV_DRIVER
*   @{
*/

#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
[!AUTOSPACING!]
[!INDENT "0"!]
[!IF "var:defined('postBuildVariant')"!]
    [!LOOP "variant:all()"!]
        #include "CanTrcv_43_AE_[!"."!]_PBcfg.h"
    [!ENDLOOP!]
[!ELSE!]
    #include "CanTrcv_43_AE_PBcfg.h"
[!ENDIF!]
/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define CANTRCV_43_AE_VENDOR_ID_CFG_H                     43
#define CANTRCV_43_AE_MODULE_ID_CFG_H                     70
#define CANTRCV_43_AE_AR_RELEASE_MAJOR_VERSION_CFG_H      4
#define CANTRCV_43_AE_AR_RELEASE_MINOR_VERSION_CFG_H      7
#define CANTRCV_43_AE_AR_RELEASE_REVISION_VERSION_CFG_H   0
#define CANTRCV_43_AE_SW_MAJOR_VERSION_CFG_H              3
#define CANTRCV_43_AE_SW_MINOR_VERSION_CFG_H              0
#define CANTRCV_43_AE_SW_PATCH_VERSION_CFG_H              0
/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/

/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
/**
*   @brief      Enable/Disable Precompile Support
*/
#define CANTRCV_43_AE_PRECOMPILE_SUPPORT[!WS "4"!][!IF "IMPLEMENTATION_CONFIG_VARIANT != 'VariantPostBuild' and (variant:size()<=1)"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Transceiver unsed
*/
#define CANTRCV_43_AE_TRANSCEIVER_UNUSED[!WS "4"!]((uint8)0xFFU)

/**
*   @brief      The definition represent for number of ECUC partition configured.
*/
[!NOCODE!]
    [!VAR "maxCoreDefConfig" = "num:i(1)"!]
    [!IF "CanTrcvGeneral/CanTrcvMulticoreSupport = 'true'"!]
        [!IF "node:exists(as:modconf('EcuC')[1]/EcucHardware/*[1]/EcucCoreDefinition)"!]
            [!VAR "maxCoreDefConfig" = "num:i(count(as:modconf('EcuC')[1]/EcucHardware/*[1]/EcucCoreDefinition/*))"!]
        [!ENDIF!]
    [!ENDIF!]
[!ENDNOCODE!]
#define CANTRCV_43_AE_MAX_PARTITIONS[!WS "4"!]([!"$maxCoreDefConfig"!]U)

[!SELECT "CanTrcvGeneral"!]
/**
*   @brief      The definition used for guarding GetCoreID/Multicore
*/
#define CANTRCV_43_AE_MULTICORE_ENABLED[!WS "4"!][!IF "num:i(count(./CanTrcvEcucPartitionRef/*)) > 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable Development Error Detection and Notification
*/
#define CANTRCV_43_AE_DEV_ERROR_DETECT[!WS "4"!][!IF "./CanTrcvDevErrorDetect = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable support CanTrcv_GetVersionInfo API
*/
#define CANTRCV_43_AE_VERSION_INFO_API[!WS "4"!][!IF "./CanTrcvVersionInfoApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable support Wakeup Mode
*/
#define CANTRCV_43_AEWAKEUP_MODE_POLLING[!WS "4"!][!IF "./CanTrcvWakeUpSupport = 'CANTRCV_WAKEUP_BY_POLLING'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Instance of the Can Hw unit
*/
#define CANTRCV_43_AE_INSTANCE[!WS "4"!]((uint8)[!"num:i(./CanTrcvIndex)"!]U)

[!IF "node:exists(./CanTrcvMainFunctionDiagnosticsPeriod)"!]
/**
*   @brief      Period for cyclic call of MainFunction Diagnostics
*/
#define CANTRCV_43_AE_MAINFUNCTIONDIAGNOSTICS_PERIOD[!WS "4"!]([!"./CanTrcvMainFunctionDiagnosticsPeriod"!]F)
[!ENDIF!]

[!IF "node:exists(./CanTrcvMainFunctionPeriod)"!]
/**
*   @brief      Period for cyclic call of MainFunction
*/
#define CANTRCV_43_AE_MAINFUNCTION_PERIOD[!WS "4"!]([!"./CanTrcvMainFunctionPeriod"!]F)
[!ENDIF!]

[!ENDSELECT!]

[!SELECT "CanTrcvConfigSet"!]
/**
*   @brief      Number Of Can Transceiver Config
*/
#define CANTRCV_43_AE_TRANSCEIVER_CONFIG_COUNT[!WS "4"!]([!"num:i(count(./CanTrcvChannel/*))"!]U)[!CR!]

/**
*   @brief      Icu driver used
*/
#define CANTRCV_43_AE_ICU_USED[!WS "4"!][!IF "node:exists(./CanTrcvChannel/*/CanTrcvIcuChannelRef)"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      EcuM driver used
*/
#define CANTRCV_43_AE_ECUM_USED[!WS "4"!][!IF "node:exists(./CanTrcvChannel/*/CanTrcvWakeupSourceRef)"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Dem driver used
*/
#define CANTRCV_43_AE_DEM_USED[!WS "4"!][!IF "node:exists(./CanTrcvChannel/*/CanTrcvDemEventParameterRefs/CANTRCV_E_BUS_ERROR)"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Indicates if the Bus Error (BUSERR) flag is managed by the BSW
*/
#define CANTRCV_43_AE_BUSERR_EN[!WS "4"!][!IF "node:exists(./CanTrcvChannel/*[CanTrcvPartialNetwork/CanTrcvBusErrFlag='true'])"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Symbolic Name generated for Can Transceiver
*/
[!LOOP "node:order(./CanTrcvChannel/*, './CanTrcvChannelId')"!]
    #define [!"@name"!][!WS "4"!]((uint8)[!"num:i(./CanTrcvChannelId)"!]U)[!CR!]
[!ENDLOOP!]

[!ENDSELECT!]

[!NOCODE!]
[!CODE!]#define CANTRCV_43_AE_CONFIG_EXT[!ENDCODE!]
[!IF "((IMPLEMENTATION_CONFIG_VARIANT != 'VariantPostBuild') and (variant:size()>1)) or (IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
    [!CODE!] \[!CR!][!ENDCODE!]
    [!INDENT "4"!]
    [!IF "var:defined('postBuildVariant')"!]
        [!VAR "variantIndex"="0"!]
        [!VAR "variantNumber"="variant:size()"!]
        [!LOOP "variant:all()"!]
            [!VAR "variantIndex"="$variantIndex + 1"!]
            [!CODE!]CANTRCV_43_AE_CONFIG_[!"."!]_PB [!IF "$variantIndex < $variantNumber"!]\[!ENDIF!][!CR!][!ENDCODE!]
        [!ENDLOOP!]
    [!ELSE!]
        [!CODE!]CANTRCV_43_AE_CONFIG_PB[!CR!][!ENDCODE!]
    [!ENDIF!]
    [!ENDINDENT!]
[!ENDIF!]
[!ENDNOCODE!]
[!ENDINDENT!]


#ifdef __cplusplus
}
#endif

/** @} */

#endif /* CANTRCV_43_AE_CFG_H */
