[!NOCODE!]
[!AUTOSPACING!]
/**
  @file    Icu_PluginMacros.m
  @version 3.0.0

  @brief   AUTOSAR Icu - plugin check.
  @details Version checks.

  Project RTD AUTOSAR 4.7
  Patform CORTEXM
  Peripheral Emios Siul2 Wkpu LpCmp
  Dependencies none

  ARVersion 4.7.0
  ARRevision ASR_REL_4_7_REV_0000
  ARConfVariant
  SWVersion 3.0.0
  BuildVersion S32K3_RTD_3_0_0_D2303_ASR_REL_4_7_REV_0000_20230331

  Copyright 2020 - 2023 NXP Semiconductors

*/

[!VAR "IcuEcucPartitionRefCount" = "num:i(count(as:modconf('Icu')[1]/IcuGeneral/IcuEcucPartitionRef/*))"!]
[!IF "$IcuEcucPartitionRefCount != 0 "!]
    [!VAR "IcuEcucPartitionRefNum" = "$IcuEcucPartitionRefCount"!] 
[!ELSE!]
    [!VAR "IcuEcucPartitionRefNum" = "1"!] 
[!ENDIF!]
[!IF "var:defined('postBuildVariant')"!]
    [!VAR "PBCfg_Variant" = "concat('PB_', $postBuildVariant)"!]
[!ELSE!]
    [!VAR "PBCfg_Variant" = "'PB'"!]
[!ENDIF!]

[!// Verify availability for EMIOS channel selected mode 
[!MACRO "VALIDATE_EMIOS_CHANNEL_MODE"!][!//
[!SELECT "IcuConfigSet"!]
    [!LOOP "IcueMios/*"!]
        [!LOOP "IcueMiosChannels/*"!]
            [!IF "not(contains(ecu:list(concat('Icu.ChannelType.','EMIOS_',node:value(../../IcueMiosModule),'_CH_',(node:value(./IcueMiosChannel)))),node:value(../../../../IcuChannel/*[(node:ref(./IcuChannelRef)/IcueMiosChannel = node:current()/IcueMiosChannel) and (node:ref(./IcuChannelRef)/../../IcueMiosModule = node:current()/../../IcueMiosModule)]/IcuMeasurementMode)))"!]
                [!ERROR!] From variant "[!"variant:name( )"!]","[!"node:path(.)"!]" The current EMIOS channel is not supported by the current Measurement Mode. [!ENDERROR!]
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDLOOP!]
[!ENDSELECT!]
[!ENDMACRO!]

[!// MACRO for creating the mapping between hardware channels and logical channels
[!// need to be called in the context of each partition where $IcuEcucPartitionRefName is available 
[!MACRO "ICU_VARIABLES"!][!//
[!NOCODE!]
    [!VAR "MaximumCoreId" = "0"!]
    [!VAR "CurrentCoreId" = "0"!]
    [!VAR "OutRespectiveCoreId" = "0"!]
    [!VAR "OutNumIcuChannelsUsingeMios" = "0"!]
    [!VAR "OutNumIcuChannelsUsingSiul2"  = "0"!]
    [!VAR "OutNumIcuChannelsUsingWkpu"  = "0"!]
    [!VAR "OutNumIcuChannelsUsingCmp"  = "0"!]
    [!VAR "OutNumIcuChannels" = "num:i(count(IcuChannel/*))"!]
    [!VAR "OutNumChannelInPartition"  = "0"!]   
    [!VAR "OutNumInstancesInPartition"  = "0"!]   
    [!// Count channels and instances in each module that is using for current partition
    [!IF "$IcuEcucPartitionRefCount != 0 "!]
        [!// Count instances
        [!LOOP "IcueMios/*"!]
            [!IF "node:exists(../../IcuChannel/*[(node:refs(IcuChannelRef)/../../IcueMiosModule = node:current()/IcueMiosModule) and (node:value(./IcuChannelEcucPartitionRef/*[1]) = $IcuEcucPartitionRefName)])"!]
                [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
            [!ENDIF!]
        [!ENDLOOP!]
        [!IF "node:exists(IcuChannel/*[(contains(node:path(node:ref(./IcuChannelRef)), 'IcuSiul2')) and (node:value(./IcuChannelEcucPartitionRef/*[1]) = $IcuEcucPartitionRefName)])"!]
            [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
        [!ENDIF!]
        [!IF "node:exists(IcuChannel/*[(contains(node:path(node:ref(./IcuChannelRef)), 'IcuWkpu')) and (contains(node:path(node:ref(./IcuChannelRef)), 'IcuWkpuChannels')) and (node:value(./IcuChannelEcucPartitionRef/*[1]) = $IcuEcucPartitionRefName)])"!]
            [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
        [!ENDIF!]
        [!LOOP "IcuLpCmp/*"!]
            [!IF "node:exists(../../IcuChannel/*[(node:refs(IcuChannelRef)/IcuCmpInstanceNumber = node:current()/IcuCmpInstanceNumber) and (node:value(./IcuChannelEcucPartitionRef/*[1]) = $IcuEcucPartitionRefName)])"!]
                [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
            [!ENDIF!]
        [!ENDLOOP!]        
        [!// Count channels
        [!LOOP "IcuChannel/*"!]
            [!VAR "HardwareModule" = "node:path(node:ref(./IcuChannelRef))"!]
            [!LOOP "./IcuChannelEcucPartitionRef/*"!]
                [!IF "node:value(.) = $IcuEcucPartitionRefName"!]
                    [!//Update variables storing number of Icu channels using either eMios, Siul2 or Wkpu IP
                    [!IF "contains($HardwareModule,'IcueMios')"!]
                        [!VAR "OutNumIcuChannelsUsingeMios" = "$OutNumIcuChannelsUsingeMios + 1"!]
                    [!ELSEIF "contains($HardwareModule,'IcuSiul2')"!]
                        [!VAR "OutNumIcuChannelsUsingSiul2" = "$OutNumIcuChannelsUsingSiul2 + 1"!]
                    [!ELSEIF "((contains($HardwareModule,'IcuWkpu')) and (contains($HardwareModule,'IcuWkpuChannels')))"!]
                        [!VAR "OutNumIcuChannelsUsingWkpu" = "$OutNumIcuChannelsUsingWkpu + 1"!]
                    [!ELSEIF "contains($HardwareModule,'IcuLpCmp')"!]
                        [!VAR "OutNumIcuChannelsUsingCmp" = "$OutNumIcuChannelsUsingCmp + 1"!]
                    [!ENDIF!]
                    [!VAR "OutNumChannelInPartition" = "$OutNumChannelInPartition + 1"!]
                [!ENDIF!]
            [!ENDLOOP!]
        [!ENDLOOP!]
        [!LOOP "../IcuGeneral/IcuEcucPartitionRef/*"!]
            [!VAR "IcuPartRefName" = "node:value(.)"!]
            [!VAR "IcuPartRefShortName" = "substring-after($IcuPartRefName, '/')"!]
            [!VAR "IcuPartRefShortName" = "substring-after($IcuPartRefShortName, '/')"!]
            [!VAR "IcuPartRefShortName" = "substring-after($IcuPartRefShortName, '/')"!]
            [!VAR "IcuPartRefShortName" = "substring-after($IcuPartRefShortName, '/')"!]
            [!VAR "IcuPartRefShortName" = "text:toupper($IcuPartRefShortName)"!]
            [!LOOP "as:modconf('Os')[1]/OsApplication/*"!]
                [!IF "node:refvalid(./OsAppEcucPartitionRef)"!]
                    [!IF "$IcuPartRefName = node:value(./OsAppEcucPartitionRef)"!]
                        [!IF "node:refvalid(./OsApplicationCoreRef)"!]
                            [!IF "$IcuPartRefName = $IcuEcucPartitionRefName"!]
                                [!VAR "OutRespectiveCoreId" = "node:value(node:ref(./OsApplicationCoreRef)/EcucCoreId)"!]
                            [!ENDIF!]
                            [!VAR "CurrentCoreId" = "node:value(node:ref(./OsApplicationCoreRef)/EcucCoreId)"!]
                            [!IF "num:i($MaximumCoreId) < num:i($CurrentCoreId)"!]
                                [!VAR "MaximumCoreId" = "$CurrentCoreId"!]
                            [!ENDIF!]
                        [!ENDIF!]
                    [!ENDIF!]
                [!ENDIF!]
            [!ENDLOOP!]
        [!ENDLOOP!]
    [!ELSE!]
        [!LOOP "IcueMios/*"!]
            [!IF "node:exists(../../IcuChannel/*[(node:refs(./IcuChannelRef)/../../IcueMiosModule = node:current()/IcueMiosModule)])"!]
                [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
            [!ENDIF!]
        [!ENDLOOP!]
        [!IF "node:exists(IcuChannel/*[(contains(node:path(node:ref(./IcuChannelRef)), 'IcuSiul2'))])"!]
            [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
        [!ENDIF!]
        [!IF "node:exists(IcuChannel/*[(contains(node:path(node:ref(./IcuChannelRef)), 'IcuWkpu')) and (contains(node:path(node:ref(./IcuChannelRef)), 'IcuWkpuChannels'))])"!]
            [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
        [!ENDIF!]
        [!LOOP "IcuLpCmp/*"!]
            [!IF "node:exists(../../IcuChannel/*[(node:refs(./IcuChannelRef)/IcuCmpInstanceNumber = node:current()/IcuCmpInstanceNumber)])"!]
                [!VAR "OutNumInstancesInPartition" = "$OutNumInstancesInPartition + 1"!]
            [!ENDIF!]
        [!ENDLOOP!]       
        [!VAR "OutNumChannelInPartition" = "num:i(count(IcuChannel/*))"!]
        [!// Count channels and instances
        [!LOOP "IcuChannel/*"!]
            [!IF "contains(node:path(node:ref(./IcuChannelRef)), 'IcueMios')"!]
                [!VAR "OutNumIcuChannelsUsingeMios" = "$OutNumIcuChannelsUsingeMios + 1"!]
            [!ELSEIF "contains(node:path(node:ref(./IcuChannelRef)), 'IcuSiul2')"!]
                [!VAR "OutNumIcuChannelsUsingSiul2" = "$OutNumIcuChannelsUsingSiul2 + 1"!]
            [!ELSEIF "((contains(node:path(node:ref(./IcuChannelRef)),'IcuWkpu')) and (contains(node:path(node:ref(./IcuChannelRef)),'IcuWkpuChannels')))"!]
                [!VAR "OutNumIcuChannelsUsingWkpu" = "$OutNumIcuChannelsUsingWkpu + 1"!]
            [!ELSEIF "contains(node:path(node:ref(./IcuChannelRef)), 'IcuLpCmp')"!]
                [!VAR "OutNumIcuChannelsUsingCmp" = "$OutNumIcuChannelsUsingCmp + 1"!]
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDIF!]
[!ENDNOCODE!]
[!ENDMACRO!][!// End of Macro ICU_VARIABLES


[!// MACRO for creating the mapping between channels and channel Index in each partition
[!MACRO "ICU_GENERATE_CHANNEL_INDEX_MAPPING","VARIANT"!]
[!NOCODE!]
    [!FOR "PartitionIdx" = "1" TO "$IcuEcucPartitionRefNum"!]
        [!IF "$IcuEcucPartitionRefCount != 0 "!]
            [!VAR "PartitionIndex" = "node:name(node:value(IcuGeneral/IcuEcucPartitionRef/*[num:i($PartitionIdx)]))"!]
            [!VAR "IcuEcucPartitionRefName" = "node:value(IcuGeneral/IcuEcucPartitionRef/*[num:i($PartitionIdx)])"!]
        [!ENDIF!]
        [!CALL "ICU_VARIABLES"!]
        [!SELECT "IcuConfigSet"!]
            [!VAR "NumIcuChannels" = "num:i(count(IcuChannel/*))"!]
[!CODE!]/*[!CR!][!ENDCODE!]
[!CODE!]*   @brief Translation LUT for Logical channel number to Partition Configuration indexed location[!CR!][!ENDCODE!]
[!CODE!]*/[!CR!][!ENDCODE!]
[!CODE!]const uint8 Icu_ChIndexMap_[!"$VARIANT"!][!IF "$IcuEcucPartitionRefCount != 0 "!]_P_[!"$PartitionIndex"!][!ENDIF!][[!"$NumIcuChannels"!]U] = [!CR!]{[!CR!][!ENDCODE!]
            [!VAR "Index" = "0"!]
            [!FOR "Idx" = "0" TO "$NumIcuChannels - 1"!]
                [!IF "$IcuEcucPartitionRefCount != 0 "!]
                    [!LOOP "./IcuChannel/*"!]
                        [!IF "num:i($Idx)=num:i(IcuChannelId)"!]
                            [!VAR "Found" = "'false'"!]
                            [!LOOP "./IcuChannelEcucPartitionRef/*"!]
                                [!IF "node:value(.) = $IcuEcucPartitionRefName"!]
                                    [!VAR "Found" = "'true'"!]
                                [!ENDIF!]
                            [!ENDLOOP!]
                            [!IF "$Found='false'"!]
[!CODE!][!WS "4"!]255U[!IF "$Idx < $NumIcuChannels - 1"!],[!ENDIF!]    /* No channel */[!CR!][!ENDCODE!]
                            [!ELSEIF "$Found='true'"!]
[!CODE!][!WS "4"!][!"num:i($Index)"!]U[!IF "$Idx < $NumIcuChannels - 1"!],[!ENDIF!]    /* [!"node:name(.)"!] has an index of [!"num:i($Index)"!] */[!CR!][!ENDCODE!]
                                [!VAR "Index" = "$Index + 1"!]
                            [!ENDIF!]
                        [!ENDIF!]
                    [!ENDLOOP!]
                [!ELSE!]
[!CODE!][!WS "4"!][!"num:i($Idx)"!]U[!IF "$Idx < $NumIcuChannels - 1"!],[!ENDIF!]    /* [!"node:name(.)"!] has an index of [!"num:i($Idx)"!] */[!CR!][!ENDCODE!]
                [!ENDIF!]
            [!ENDFOR!]
[!CODE!]};[!ENDCODE!]
        [!ENDSELECT!]
    [!ENDFOR!]
[!ENDNOCODE!]
[!ENDMACRO!]

[!ENDNOCODE!]